behaviors:
  TenTen:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 16384
      learning_rate: 0.0003
      beta: 5.0e-3
      epsilon: 0.21
      lambd: 0.99
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: match3
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 6000000
    time_horizon: 128
    summary_freq: 10000
